### ISSUE TITLE
Path to Stage 4!

### ISSUE THREAD

**Issue by ljharb** [ljharb/proposal-array-zip#3]
## Stage 4
 - [ ] committee approval
 - [ ] two implementations
 - [ ] significant in-the-field experience
 - [ ] ecma262 PR approved
 - [ ] prepare ecma262 PR
 - [ ] [Joint Iteration proposal](https://github.com/tc39/proposal-joint-iteration) advances to stage 4

## Stage 3
 - [ ] committee approval
 - [ ] merge test262 tests
 - [ ] write test262 tests
 - [ ] [Joint Iteration proposal](https://github.com/tc39/proposal-joint-iteration) advances to stage 3

## Stage 2.7
 - [ ] committee approval
 - [ ] spec editor signoff
   - [ ] `@syg`
   - [ ] `@bakkot`
   - [ ] `@michaelficarra`
 - [ ] spec reviewer signoff

## Stage 2
 - [ ] committee approval
 - [ ] spec reviewers selected
 - [ ] spec text written

## Stage 1
 - [ ] committee approval
